# Generated by Django 4.0.6 on 2022-07-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=600)),
                ('sender', models.EmailField(max_length=254)),
                ('uuid', models.UUIDField(verbose_name='id')),
            ],
        ),
    ]
