# Generated by Django 4.0.6 on 2022-07-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacted',
            name='uuid',
            field=models.CharField(max_length=200, verbose_name='id'),
        ),
    ]
