# Generated by Django 4.0.6 on 2022-07-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_contacted_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacted',
            name='id',
        ),
        migrations.AlterField(
            model_name='contacted',
            name='uuid',
            field=models.IntegerField(max_length=200, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
