# Generated by Django 4.0.6 on 2022-07-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_contacted_id_alter_contacted_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacted',
            name='uuid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
